import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import lora from "./fonts/Lora";




export const metadata: Metadata = {
  title: "A&J Bisutería",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
